/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateJobRequest {
  'roomImageBlob' : ExternalBlob,
  'decorItems' : Array<DecorItem>,
  'style' : Style,
}
export interface CreateJobResponse {
  'status' : JobStatus,
  'jobId' : bigint,
  'timestamp' : Time,
}
export type DecorItem = string;
export interface DesignJob {
  'timerange' : Time,
  'status' : JobStatus,
  'output' : [] | [JobOutput],
  'userId' : UserId,
  'jobId' : bigint,
  'decorItems' : Array<DecorItem>,
  'style' : Style,
}
export type ExternalBlob = Uint8Array;
export interface JobOutput { 'description' : string, 'imageId' : string }
export type JobStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type Style = { 'indianTraditional' : null } |
  { 'scandinavian' : null } |
  { 'minimalist' : null } |
  { 'modern' : null } |
  { 'luxury' : null };
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJob' : ActorMethod<[CreateJobRequest], CreateJobResponse>,
  'getAllJobs' : ActorMethod<[], Array<DesignJob>>,
  'getCallerJobs' : ActorMethod<[], Array<DesignJob>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDecorItems' : ActorMethod<[], Array<DecorItem>>,
  'getJobById' : ActorMethod<[bigint], [] | [DesignJob]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateJobStatus' : ActorMethod<[bigint, JobStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];