/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DecorItem = IDL.Text;
export const Style = IDL.Variant({
  'indianTraditional' : IDL.Null,
  'scandinavian' : IDL.Null,
  'minimalist' : IDL.Null,
  'modern' : IDL.Null,
  'luxury' : IDL.Null,
});
export const CreateJobRequest = IDL.Record({
  'roomImageBlob' : ExternalBlob,
  'decorItems' : IDL.Vec(DecorItem),
  'style' : Style,
});
export const JobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const CreateJobResponse = IDL.Record({
  'status' : JobStatus,
  'jobId' : IDL.Nat,
  'timestamp' : Time,
});
export const JobOutput = IDL.Record({
  'description' : IDL.Text,
  'imageId' : IDL.Text,
});
export const UserId = IDL.Principal;
export const DesignJob = IDL.Record({
  'timerange' : Time,
  'status' : JobStatus,
  'output' : IDL.Opt(JobOutput),
  'userId' : UserId,
  'jobId' : IDL.Nat,
  'decorItems' : IDL.Vec(DecorItem),
  'style' : Style,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJob' : IDL.Func([CreateJobRequest], [CreateJobResponse], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(DesignJob)], ['query']),
  'getCallerJobs' : IDL.Func([], [IDL.Vec(DesignJob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDecorItems' : IDL.Func([], [IDL.Vec(DecorItem)], ['query']),
  'getJobById' : IDL.Func([IDL.Nat], [IDL.Opt(DesignJob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateJobStatus' : IDL.Func([IDL.Nat, JobStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DecorItem = IDL.Text;
  const Style = IDL.Variant({
    'indianTraditional' : IDL.Null,
    'scandinavian' : IDL.Null,
    'minimalist' : IDL.Null,
    'modern' : IDL.Null,
    'luxury' : IDL.Null,
  });
  const CreateJobRequest = IDL.Record({
    'roomImageBlob' : ExternalBlob,
    'decorItems' : IDL.Vec(DecorItem),
    'style' : Style,
  });
  const JobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const CreateJobResponse = IDL.Record({
    'status' : JobStatus,
    'jobId' : IDL.Nat,
    'timestamp' : Time,
  });
  const JobOutput = IDL.Record({
    'description' : IDL.Text,
    'imageId' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const DesignJob = IDL.Record({
    'timerange' : Time,
    'status' : JobStatus,
    'output' : IDL.Opt(JobOutput),
    'userId' : UserId,
    'jobId' : IDL.Nat,
    'decorItems' : IDL.Vec(DecorItem),
    'style' : Style,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJob' : IDL.Func([CreateJobRequest], [CreateJobResponse], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(DesignJob)], ['query']),
    'getCallerJobs' : IDL.Func([], [IDL.Vec(DesignJob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDecorItems' : IDL.Func([], [IDL.Vec(DecorItem)], ['query']),
    'getJobById' : IDL.Func([IDL.Nat], [IDL.Opt(DesignJob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateJobStatus' : IDL.Func([IDL.Nat, JobStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };